repos:
  - repo_owner: kingfadzi
    repo_name: scan_scheduler
    branch: plugins
    target_dir: /home/fadzi/tools/scan_scheduler
    enabled: false
    skip_patterns: []

  - repo_owner: kingfadzi
    repo_name: config=files
    branch: main
    target_dir: /home/fadzi/tools/config
    skip_patterns: []
    enabled: false
